flowControl and loops
KarlisTi/Codelex_March pull request #1
Opened 2022-03-04 19:14 UTC by KarlisTi

2022-03-06 19:17 UTC, NilsKula requested changes
varbūt palaidu garām, bet neredzeju
loop - 3rd task
flow - 2, 3, 5

2022-03-06 19:17 UTC, NilsKula commented on src/main/java/io/codelex/loops/FizzBuzz.java
> +public class FizzBuzz {
šēit ar inut vajadzeja 
`Write a console program in a class named FizzBuzz that prompts the user for an integer, then prints all of the numbers from one to that integer, separated by spaces.` :smile:

2022-03-06 19:17 UTC, NilsKula commented on src/main/java/io/codelex/loops/Piglet.java
> +            String newInput = scan.next();
`toLowerCase()` noteikti nenāktu par sliktu

2022-03-06 19:17 UTC, NilsKula commented on src/main/java/io/codelex/loops/ASCIIFigure.java
> +        int value = classConstant * 4;
arī 4 un 8 būtu labi nodefinēt, lai nav `magic numbers`

2022-03-06 19:17 UTC, NilsKula commented on src/main/java/io/codelex/flowcontrol/Exercise2.java
> +        } else if (num2 > num1 && num2 > num3) {
nav nepieciešams salīdzināt `num2 > num1`, šajā brīdi jau zināms, ka num1 nav lielākais

2022-03-06 19:17 UTC, NilsKula commented on src/main/java/io/codelex/flowcontrol/PrintDayInWord.java
> +//public class PrintDayInWord {
pietrūkst `not a valid day` validācija

2022-03-15 17:53 UTC, KarlisTi commented
> varbūt palaidu garām, bet neredzeju loop - 3rd task flow - 2, 3, 5

Pielik trešo uzdevumu Loop.

Parējie visi bija

2022-03-15 17:53 UTC, merged

2022-03-15 23:05 UTC, NilsKula commented on src/main/java/io/codelex/loops/Exercise4.java
> +        for(int var4 = 0; var4 < var3; ++var4) {
te domāts `for(char vowel : vowels)`