Class
KarlisTi/Codelex_March pull request #3
Opened 2022-03-14 14:03 UTC by KarlisTi

2022-03-15 20:45 UTC, KarlisTi commented
11. udevums vēl nav līdz galam pabeigts

2022-03-18 15:35 UTC, NilsKula requested changes
formatting stuff un variabļus ne ar vienu burtu

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise1/Product.java
> +    public static void printProduct(String a, double b, int c) {
davai mēgināsim bez viena burta variabļu nosaukumiem :smile:

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise10/BankAccount_main.java
> +public class BankAccount_main {
klases bez underscore

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise10/BankAccount.java
> +        return name + ", " + String.valueOf(balance);
` If the balance is negative, put the - sign before the dollar sign. Also, always display the cents as a two-digit number. For example, if the same object had a balance of -17.5`

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise2/Car.java
> +public class Car {
secība klasē
- variables
- constructor
- methods

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise2/Car.java
> +            return a > 15.0;
constant

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise3/Odometer.java
> +        if (this.mileage < 999999) {
constant

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise3/CarTest.java
> +        while (fuel.getFuelInLiters() < 70) {
constant

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise4/Movie.java
> +                ;
:thinking:

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise5/Date.java
> +
secība

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise7/Dog.java
> +    private String sex;
laba vieta priekš enum

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise7/Dog.java
> +
formatting, unnecessary multiple empty lines

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise7/Dog.java
> +        if (this.mother.equals(otherDog.mother)) {
hanlde null mother

2022-03-18 15:35 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/Exercise8/SavingAccount.java
> +    private double getTotalDeposited = 0;
primitives ir dedault value, var iztikt bez `= 0`

2022-03-23 09:01 UTC, KarlisTi reviewed
Izgāju cauri.

2022-03-25 18:16 UTC, KarlisTi reviewed
Visu pārskatīju

2022-03-25 18:17 UTC, KarlisTi reviewed
Done

2022-03-27 07:11 UTC, NilsKula approved these changes

2022-03-27 13:42 UTC, KarlisTi reviewed
Done

2022-03-29 09:37 UTC, merged