OOP
KarlisTi/Codelex_March pull request #5
Opened 2022-03-23 13:45 UTC by KarlisTi

2022-03-29 21:09 UTC, NilsKula requested changes

2022-03-29 21:09 UTC, NilsKula commented on src/main/java/io/codelex/oop/Cars/Car.java
> +        return price == car.price && yearOfManafacture == car.yearOfManafacture && Objects.equals(name, car.name) && Objects.equals(model, car.model) && Objects.equals(manufacturer, car.manufacturer)
if you have to scroll to the left, the line is too long 😄
https://www.oracle.com/java/technologies/javase/codeconventions-indentation.html

2022-03-29 21:09 UTC, NilsKula commented on src/main/java/io/codelex/oop/Cars/CarService.java
> +    public void returnCarsWithThreeManufaturer() {
arī ka variable varētu padot to 3

2022-03-29 21:09 UTC, NilsKula commented on src/main/java/io/codelex/oop/Cars/CarService.java
> +            for (Manafacturer list : carList.getManufacturer()) {
šo varētu kā palīgmetodi `cars` klasē

2022-03-29 21:09 UTC, NilsKula commented on src/main/java/io/codelex/oop/Cars/Manafacturer.java
> +    String CompanyName;
private

2022-03-29 21:09 UTC, NilsKula commented on src/main/java/io/codelex/oop/Exercise2/Employee.java
> +        long workExpierence = ChronoUnit.YEARS.between(startDate, today);
`return ChronoUnit.YEARS.between(startDate, today)`

2022-03-29 21:09 UTC, NilsKula commented on src/main/java/io/codelex/oop/Exercise4/mainClass.java
> +public class mainClass {
lielais burts

2022-03-29 21:09 UTC, NilsKula commented on src/main/java/io/codelex/oop/Parcels/Parcel.java
> +        if (xLength + yLength + zLength > 300) {
constants/helper methods

2022-04-01 10:05 UTC, KarlisTi reviewed
Pārskatīju

2022-04-01 10:05 UTC, KarlisTi commented on src/main/java/io/codelex/oop/Parcels/Parcel.java
> +        if (xLength + yLength + zLength > 300) {
salaboju

2022-04-15 16:56 UTC, NilsKula approved these changes

2022-04-15 16:56 UTC, NilsKula commented on src/main/java/io/codelex/oop/Cars/CarService.java
> +    public void returnCarsWithThreeManufaturer() {
šeit biju domājis pašai metodei padot, tādā veidā izveidojot viņu generic 
piemēram `returnCarsByManufacturerCount(int manufacturerSize)`
tādā veidā tev nebūs jātaisa jauna metode ja gribēsi pēkšņi piemēŗam ar vismaz 5 manufacturers

2022-04-15 16:56 UTC, NilsKula commented on src/main/java/io/codelex/oop/Cars/CarService.java
> +            for (Manafacturer list : carList.getManufacturer()) {
doma ir tāda, ka manufacturer list pieder mašīnas objektam
piemēram `car.hasManufacturer(name)` 
```
for (Car carList : cars) {
            if (car.hasManufacturer(name)) {
                      System.out.println(carList.getName());
           }
```

šķīet būs īsāk lasāmāk 😄 
but this is more liek good thing to have

2022-04-27 14:07 UTC, merged